Based on the code updates from the main branch, improve the code to resolve new compilation errors: >>> defined in rust/workspace/lib_ch_rust_skim_rust.a(c16f17691ff6f04b-cxx.o) >>> referenced by cxx.cc >>>               c16f17691ff6f04b-cxx.o:(cxxbridge1$error) in archive rust/workspace/lib_ch_rust_skim_rust.a
ld.lld-21: error: relocation refers to a symbol in a discarded section: __clang_call_terminate
>>> defined in rust/workspace/lib_ch_rust_skim_rust.a(5e90aa4320e3cf3c-lib.rs.o)
>>> referenced by lib.rs.cc
>>>               5e90aa4320e3cf3c-lib.rs.o:(rust::cxxbridge1::(anonymous namespace)::impl<rust::cxxbridge1::Error>::error(rust::cxxbridge1::repr::PtrLen)) in archive rust/workspace/lib_ch_rust_skim_rust.a

ld.lld-21: error: relocation refers to a symbol in a discarded section: DW.ref.__gxx_personality_v0
>>> defined in rust/workspace/lib_ch_rust_skim_rust.a(5e90aa4320e3cf3c-lib.rs.o)
>>> referenced by lib.rs.cc
>>>               5e90aa4320e3cf3c-lib.rs.o:(.eh_frame+0x21d32ab) in archive rust/workspace/lib_ch_rust_skim_rust.a

ld.lld-21: error: relocation refers to a symbol in a discarded section: DW.ref.__gxx_personality_v0
>>> defined in rust/workspace/lib_ch_rust_skim_rust.a(c16f17691ff6f04b-cxx.o)
>>> referenced by cxx.cc
>>>               c16f17691ff6f04b-cxx.o:(.eh_frame+0x2472d07) in archive rust/workspace/lib_ch_rust_skim_rust.a
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.